/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package dcat.impl;

import dcat.Dataset;
import dcat.DatasetSeries;
import dcat.DcatPackage;
import dcat.Distribution;

import java.math.BigDecimal;

import java.util.Collection;

import javax.xml.datatype.Duration;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EDataTypeUniqueEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import terms.Location;
import terms.PeriodOfTime;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dataset</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dcat.impl.DatasetImpl#getDistribution <em>Distribution</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getSpatialResolutionInMeters <em>Spatial Resolution In Meters</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getTemporalResolution <em>Temporal Resolution</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getAccrualPeriodicity <em>Accrual Periodicity</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getSpatial <em>Spatial</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getTemporal <em>Temporal</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getWasGeneratedBy <em>Was Generated By</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getInSeries <em>In Series</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link dcat.impl.DatasetImpl#getHasVersion <em>Has Version</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DatasetImpl extends DcatResourceImpl implements Dataset {
	/**
	 * The cached value of the '{@link #getDistribution() <em>Distribution</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getDistribution()
	 * @generated
	 * @ordered
	 */
	protected EList<Distribution> distribution;

	/**
	 * The default value of the '{@link #getSpatialResolutionInMeters() <em>Spatial Resolution In Meters</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSpatialResolutionInMeters()
	 * @generated
	 * @ordered
	 */
	protected static final BigDecimal SPATIAL_RESOLUTION_IN_METERS_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getSpatialResolutionInMeters() <em>Spatial Resolution In Meters</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSpatialResolutionInMeters()
	 * @generated
	 * @ordered
	 */
	protected BigDecimal spatialResolutionInMeters = SPATIAL_RESOLUTION_IN_METERS_EDEFAULT;

	/**
	 * The default value of the '{@link #getTemporalResolution() <em>Temporal Resolution</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTemporalResolution()
	 * @generated
	 * @ordered
	 */
	protected static final Duration TEMPORAL_RESOLUTION_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getTemporalResolution() <em>Temporal Resolution</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTemporalResolution()
	 * @generated
	 * @ordered
	 */
	protected Duration temporalResolution = TEMPORAL_RESOLUTION_EDEFAULT;

	/**
	 * The default value of the '{@link #getAccrualPeriodicity() <em>Accrual Periodicity</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAccrualPeriodicity()
	 * @generated
	 * @ordered
	 */
	protected static final String ACCRUAL_PERIODICITY_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getAccrualPeriodicity() <em>Accrual Periodicity</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAccrualPeriodicity()
	 * @generated
	 * @ordered
	 */
	protected String accrualPeriodicity = ACCRUAL_PERIODICITY_EDEFAULT;

	/**
	 * The cached value of the '{@link #getSpatial() <em>Spatial</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getSpatial()
	 * @generated
	 * @ordered
	 */
	protected EList<Location> spatial;

	/**
	 * The cached value of the '{@link #getTemporal() <em>Temporal</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTemporal()
	 * @generated
	 * @ordered
	 */
	protected EList<PeriodOfTime> temporal;

	/**
	 * The cached value of the '{@link #getWasGeneratedBy() <em>Was Generated By</em>}' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getWasGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected EList<String> wasGeneratedBy;

	/**
	 * The cached value of the '{@link #getInSeries() <em>In Series</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getInSeries()
	 * @generated
	 * @ordered
	 */
	protected EList<DatasetSeries> inSeries;

	/**
	 * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVersion()
	 * @generated
	 * @ordered
	 */
	protected static final String VERSION_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVersion()
	 * @generated
	 * @ordered
	 */
	protected String version = VERSION_EDEFAULT;

	/**
	 * The cached value of the '{@link #getHasVersion() <em>Has Version</em>}' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getHasVersion()
	 * @generated
	 * @ordered
	 */
	protected EList<String> hasVersion;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatasetImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return DcatPackage.Literals.DATASET;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Distribution> getDistribution() {
		if (distribution == null) {
			distribution = new EObjectContainmentEList<Distribution>(Distribution.class, this, DcatPackage.DATASET__DISTRIBUTION);
		}
		return distribution;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BigDecimal getSpatialResolutionInMeters() {
		return spatialResolutionInMeters;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setSpatialResolutionInMeters(BigDecimal newSpatialResolutionInMeters) {
		BigDecimal oldSpatialResolutionInMeters = spatialResolutionInMeters;
		spatialResolutionInMeters = newSpatialResolutionInMeters;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DcatPackage.DATASET__SPATIAL_RESOLUTION_IN_METERS, oldSpatialResolutionInMeters, spatialResolutionInMeters));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Duration getTemporalResolution() {
		return temporalResolution;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setTemporalResolution(Duration newTemporalResolution) {
		Duration oldTemporalResolution = temporalResolution;
		temporalResolution = newTemporalResolution;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DcatPackage.DATASET__TEMPORAL_RESOLUTION, oldTemporalResolution, temporalResolution));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getAccrualPeriodicity() {
		return accrualPeriodicity;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setAccrualPeriodicity(String newAccrualPeriodicity) {
		String oldAccrualPeriodicity = accrualPeriodicity;
		accrualPeriodicity = newAccrualPeriodicity;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DcatPackage.DATASET__ACCRUAL_PERIODICITY, oldAccrualPeriodicity, accrualPeriodicity));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Location> getSpatial() {
		if (spatial == null) {
			spatial = new EObjectContainmentEList<Location>(Location.class, this, DcatPackage.DATASET__SPATIAL);
		}
		return spatial;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<PeriodOfTime> getTemporal() {
		if (temporal == null) {
			temporal = new EObjectContainmentEList<PeriodOfTime>(PeriodOfTime.class, this, DcatPackage.DATASET__TEMPORAL);
		}
		return temporal;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<String> getWasGeneratedBy() {
		if (wasGeneratedBy == null) {
			wasGeneratedBy = new EDataTypeEList<String>(String.class, this, DcatPackage.DATASET__WAS_GENERATED_BY);
		}
		return wasGeneratedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<DatasetSeries> getInSeries() {
		if (inSeries == null) {
			inSeries = new EObjectResolvingEList<DatasetSeries>(DatasetSeries.class, this, DcatPackage.DATASET__IN_SERIES);
		}
		return inSeries;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setVersion(String newVersion) {
		String oldVersion = version;
		version = newVersion;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DcatPackage.DATASET__VERSION, oldVersion, version));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<String> getHasVersion() {
		if (hasVersion == null) {
			hasVersion = new EDataTypeUniqueEList<String>(String.class, this, DcatPackage.DATASET__HAS_VERSION);
		}
		return hasVersion;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case DcatPackage.DATASET__DISTRIBUTION:
				return ((InternalEList<?>)getDistribution()).basicRemove(otherEnd, msgs);
			case DcatPackage.DATASET__SPATIAL:
				return ((InternalEList<?>)getSpatial()).basicRemove(otherEnd, msgs);
			case DcatPackage.DATASET__TEMPORAL:
				return ((InternalEList<?>)getTemporal()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case DcatPackage.DATASET__DISTRIBUTION:
				return getDistribution();
			case DcatPackage.DATASET__SPATIAL_RESOLUTION_IN_METERS:
				return getSpatialResolutionInMeters();
			case DcatPackage.DATASET__TEMPORAL_RESOLUTION:
				return getTemporalResolution();
			case DcatPackage.DATASET__ACCRUAL_PERIODICITY:
				return getAccrualPeriodicity();
			case DcatPackage.DATASET__SPATIAL:
				return getSpatial();
			case DcatPackage.DATASET__TEMPORAL:
				return getTemporal();
			case DcatPackage.DATASET__WAS_GENERATED_BY:
				return getWasGeneratedBy();
			case DcatPackage.DATASET__IN_SERIES:
				return getInSeries();
			case DcatPackage.DATASET__VERSION:
				return getVersion();
			case DcatPackage.DATASET__HAS_VERSION:
				return getHasVersion();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case DcatPackage.DATASET__DISTRIBUTION:
				getDistribution().clear();
				getDistribution().addAll((Collection<? extends Distribution>)newValue);
				return;
			case DcatPackage.DATASET__SPATIAL_RESOLUTION_IN_METERS:
				setSpatialResolutionInMeters((BigDecimal)newValue);
				return;
			case DcatPackage.DATASET__TEMPORAL_RESOLUTION:
				setTemporalResolution((Duration)newValue);
				return;
			case DcatPackage.DATASET__ACCRUAL_PERIODICITY:
				setAccrualPeriodicity((String)newValue);
				return;
			case DcatPackage.DATASET__SPATIAL:
				getSpatial().clear();
				getSpatial().addAll((Collection<? extends Location>)newValue);
				return;
			case DcatPackage.DATASET__TEMPORAL:
				getTemporal().clear();
				getTemporal().addAll((Collection<? extends PeriodOfTime>)newValue);
				return;
			case DcatPackage.DATASET__WAS_GENERATED_BY:
				getWasGeneratedBy().clear();
				getWasGeneratedBy().addAll((Collection<? extends String>)newValue);
				return;
			case DcatPackage.DATASET__IN_SERIES:
				getInSeries().clear();
				getInSeries().addAll((Collection<? extends DatasetSeries>)newValue);
				return;
			case DcatPackage.DATASET__VERSION:
				setVersion((String)newValue);
				return;
			case DcatPackage.DATASET__HAS_VERSION:
				getHasVersion().clear();
				getHasVersion().addAll((Collection<? extends String>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case DcatPackage.DATASET__DISTRIBUTION:
				getDistribution().clear();
				return;
			case DcatPackage.DATASET__SPATIAL_RESOLUTION_IN_METERS:
				setSpatialResolutionInMeters(SPATIAL_RESOLUTION_IN_METERS_EDEFAULT);
				return;
			case DcatPackage.DATASET__TEMPORAL_RESOLUTION:
				setTemporalResolution(TEMPORAL_RESOLUTION_EDEFAULT);
				return;
			case DcatPackage.DATASET__ACCRUAL_PERIODICITY:
				setAccrualPeriodicity(ACCRUAL_PERIODICITY_EDEFAULT);
				return;
			case DcatPackage.DATASET__SPATIAL:
				getSpatial().clear();
				return;
			case DcatPackage.DATASET__TEMPORAL:
				getTemporal().clear();
				return;
			case DcatPackage.DATASET__WAS_GENERATED_BY:
				getWasGeneratedBy().clear();
				return;
			case DcatPackage.DATASET__IN_SERIES:
				getInSeries().clear();
				return;
			case DcatPackage.DATASET__VERSION:
				setVersion(VERSION_EDEFAULT);
				return;
			case DcatPackage.DATASET__HAS_VERSION:
				getHasVersion().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case DcatPackage.DATASET__DISTRIBUTION:
				return distribution != null && !distribution.isEmpty();
			case DcatPackage.DATASET__SPATIAL_RESOLUTION_IN_METERS:
				return SPATIAL_RESOLUTION_IN_METERS_EDEFAULT == null ? spatialResolutionInMeters != null : !SPATIAL_RESOLUTION_IN_METERS_EDEFAULT.equals(spatialResolutionInMeters);
			case DcatPackage.DATASET__TEMPORAL_RESOLUTION:
				return TEMPORAL_RESOLUTION_EDEFAULT == null ? temporalResolution != null : !TEMPORAL_RESOLUTION_EDEFAULT.equals(temporalResolution);
			case DcatPackage.DATASET__ACCRUAL_PERIODICITY:
				return ACCRUAL_PERIODICITY_EDEFAULT == null ? accrualPeriodicity != null : !ACCRUAL_PERIODICITY_EDEFAULT.equals(accrualPeriodicity);
			case DcatPackage.DATASET__SPATIAL:
				return spatial != null && !spatial.isEmpty();
			case DcatPackage.DATASET__TEMPORAL:
				return temporal != null && !temporal.isEmpty();
			case DcatPackage.DATASET__WAS_GENERATED_BY:
				return wasGeneratedBy != null && !wasGeneratedBy.isEmpty();
			case DcatPackage.DATASET__IN_SERIES:
				return inSeries != null && !inSeries.isEmpty();
			case DcatPackage.DATASET__VERSION:
				return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
			case DcatPackage.DATASET__HAS_VERSION:
				return hasVersion != null && !hasVersion.isEmpty();
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString() {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (spatialResolutionInMeters: ");
		result.append(spatialResolutionInMeters);
		result.append(", temporalResolution: ");
		result.append(temporalResolution);
		result.append(", accrualPeriodicity: ");
		result.append(accrualPeriodicity);
		result.append(", wasGeneratedBy: ");
		result.append(wasGeneratedBy);
		result.append(", version: ");
		result.append(version);
		result.append(", hasVersion: ");
		result.append(hasVersion);
		result.append(')');
		return result.toString();
	}

} //DatasetImpl
